# Generated by Django 4.1.3 on 2022-11-21 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TimeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('internal_note', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('max_spots', models.IntegerField(default=1)),
                ('display_current_spots_number', models.BooleanField(default=False)),
                ('color_hex_code', models.CharField(max_length=7)),
                ('event_link', models.CharField(max_length=50, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=36)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=36, null=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservations.eventtype')),
                ('time_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservations.timeunit')),
            ],
        ),
    ]
