# Generated by Django 4.1.3 on 2022-11-30 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationevent',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='reservationevent',
            name='time_unit',
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
        migrations.DeleteModel(
            name='ReservationEvent',
        ),
        migrations.DeleteModel(
            name='TimeUnit',
        ),
    ]
